### PR TITLE
Various bug fixes

### LINKED ISSUE #113: In ign_system.cpp, VELOCITY and POSITION command modes are conflicting
Check this out:

```
    if (this->dataPtr->joints_[i].joint_control_method & VELOCITY) {
      ...
        *jointVelCmd = ignition::gazebo::components::JointVelocityCmd(
          {this->dataPtr->joints_[i].joint_velocity_cmd});
      }
    }

    if (this->dataPtr->joints_[i].joint_control_method & POSITION) {
      ...
        vel->Data()[0] = targetVel;
      }
    }

    if (this->dataPtr->joints_[i].joint_control_method & EFFORT) {
      ...
        *jointEffortCmd = ignition::gazebo::components::JointForceCmd(
          {this->dataPtr->joints_[i].joint_effort_cmd});
      }
    }
  }
```

There are some issues:

- VELOCITY can set a target velocity, then POSITION can set a different velocity target. In other words, POSITION overrides the effect of VELOCITY.
- All of POSITION, VELOCITY, and EFFORT can be active at any time. This does not seem right -- only 1 should be active.
- There's no PID gain specified in calculating the POSITION command. The gain is 1.
- When I send a position command to just one joint (for example), the other joints tend to sag downward with gravity.

Related to #87

### PR DESCRIPTION
**Pull request by AndyZe**
Fixes #113. To quote from that issue:

```
    if (this->dataPtr->joints_[i].joint_control_method & VELOCITY) {
      ...
        *jointVelCmd = ignition::gazebo::components::JointVelocityCmd(
          {this->dataPtr->joints_[i].joint_velocity_cmd});
      }
    }

    if (this->dataPtr->joints_[i].joint_control_method & POSITION) {
      ...
        vel->Data()[0] = targetVel;
      }
    }

    if (this->dataPtr->joints_[i].joint_control_method & EFFORT) {
      ...
        *jointEffortCmd = ignition::gazebo::components::JointForceCmd(
          {this->dataPtr->joints_[i].joint_effort_cmd});
      }
    }
  }
```

Here are some of the bugs in that code:

- VELOCITY can set a target velocity, then POSITION can set a different velocity target. In other words, POSITION overrides the effect of VELOCITY.
- All of POSITION, VELOCITY, and EFFORT can be active at any time. This does not seem right -- only 1 should be active.
- There's no PID gain specified in calculating the POSITION command. The gain is 1.
- When I send a position command to just one joint (for example), the other joints tend to sag downward with gravity.

Here's a "before" video. It's hard to see but note that the "upper_arm_link" of the robot is always drooping down with gravity although only the elbow joint is actuated.

https://user-images.githubusercontent.com/11284393/215857956-0dd515c4-7083-4fbd-a177-6714a3e34479.mp4

Here's an "after" video showing no droop of other joints besides the actuated elbow.

no_droop

### CODE REVIEW

File: ign_ros2_control/src/ign_system.cpp [hunk 1]
```diff
@@ -173,8 +175,14 @@ bool IgnitionSystem::initSim(
 
   this->dataPtr->joints_.resize(this->dataPtr->n_dof_);
 
+  constexpr double default_gain = 0.1;
+  if (!this->nh_->get_parameter_or("position_proportional_gain", this->dataPtr->position_proportional_gain_, default_gain))
```
Comment (AndyZe) [inline ign_ros2_control/src/ign_system.cpp:179]: An optional gain parameter. Previously it was hard-coded to 1.0.

File: ign_ros2_control/src/ign_system.cpp [hunk 2]
```diff
@@ -532,13 +540,13 @@ IgnitionSystem::perform_command_mode_switch(
         this->dataPtr->joints_[j].joint_control_method &=
           static_cast<ControlMethod_>(VELOCITY & EFFORT);
       }
-      if (interface_name == (this->dataPtr->joints_[j].name + "/" +
+      else if (interface_name == (this->dataPtr->joints_[j].name + "/" +
```
Comment (AndyZe) [inline ign_ros2_control/src/ign_system.cpp:543]: Small efficiency improvement

File: ign_ros2_control/src/ign_system.cpp [hunk 3]
```diff
@@ -627,6 +637,25 @@ hardware_interface::return_type IgnitionSystem::write(
           {this->dataPtr->joints_[i].joint_effort_cmd});
       }
     }
+
+    // Fallback case is a velocity command of zero
```
Comment (AndyZe) [inline ign_ros2_control/src/ign_system.cpp:640]: I think this is what prevented the unactuated joints from drooping with gravity.

File: ign_ros2_control/src/ign_system.cpp [hunk 4]
```diff
@@ -590,14 +599,14 @@ hardware_interface::return_type IgnitionSystem::write(
       }
     }
 
-    if (this->dataPtr->joints_[i].joint_control_method & POSITION) {
+    else if (this->dataPtr->joints_[i].joint_control_method & POSITION) {
```
Comment (AndyZe) [inline ign_ros2_control/src/ign_system.cpp:602]: else-if so the velocity command from this interface doesn't conflict with the one at L597

**Comment by AndyZe** [comment]
ament_cpp_lint conflicts with one of the other linters:

`
 /home/ros2_ws/src/gz_ros2_control/ign_ros2_control/src/ign_system.cpp:547:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]`

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@AndyZe do you have any plans to include these fixes in `gazebo_ros2_control` ? Let me know if you don't have time and I will do it

**Comment by AndyZe** [comment]
I don't mind making a quick PR to `gazebo_ros2_control`  :+1:

I actually wasn't aware of `gazebo_ros2_control` prior to this. Is that the recommended way?

**Comment by ahcorde** [comment]
We need to support Gazebo classic too, the code is pretty similar, when something is added here or there I try to keep both repositories up to day. If the contributor is open to do it it's fantastic otherwise I will do it. 

By the way, thank you for your contribution.
