### PR TITLE
Fixed velocity controller

### LINKED ISSUE #469: Velocity command interface is broken on rolling+ionic
**Describe the bug**
Velocity command interface is broken on rolling+ionic? position interfaces work

**To Reproduce**
1. `ros2 launch gz_ros2_control_demos diff_drive_example.launch.py`
2. `ros2 run gz_ros2_control_demos example_diff_drive `
3. nothing moves

same with cart_velocity example

**Environment (please complete the following information):**
 - OS: Ubuntu noble
 - Version rolling from source, ros-rolling-gz-sim-vendor 0.2.0, ionic 9.0.0

**Additional context**
The same examples work on humble+fortress.

### PR DESCRIPTION
**Pull request by ahcorde**
Just testing a PR I noticed that velocity controllers were not working. I made this quick fix but I'm not sure if this will break other users

@christophfroehlich any thoughts?

### CODE REVIEW

**Comment by ahcorde** [comment]
@azeey do you know why the `JointVelocityCmd` is destroyed ? and I have to create a new one every iteration ?

this is not happening with position and effort

File: gz_ros2_control/src/gz_system.cpp [hunk 1]
```diff
@@ -654,7 +654,7 @@ hardware_interface::return_type GazeboSimSystem::write(
       {
         this->dataPtr->ecm->CreateComponent(
           this->dataPtr->joints_[i].sim_joint,
-          sim::components::JointVelocityCmd({0}));
+          sim::components::JointVelocityCmd({this->dataPtr->joints_[i].joint_velocity_cmd}));
```
Comment (azeey) [inline gz_ros2_control/src/gz_system.cpp]: This can be simplified by using the [`SetComponentData`](https://gazebosim.org/api/sim/9/classgz_1_1sim_1_1EntityComponentManager.html#ada2c5008634545bbb5d9cb3a14a3aecf) function, so it would just look like:

```c++
this->dataPtr->ecm->SetComponentData(this->dataPtr->joints_[i].sim_joint, {this->dataPtr->joints_[i].sim_joint})
```
replacing the entire if/else block starting with ` if (!this->dataPtr->ecm->Component<sim::components::JointVelocityCmd>(
          this->dataPtr->joints_[i].sim_joint))`

**Review by azeey — APPROVED** [review]

**Review by christophfroehlich — APPROVED** [review]
Thanks @azeey @ahcorde 
I can confirm that my reported issue is fixed now.
